import {
  BanknotesIcon,
  BriefcaseIcon,
  BuildingLibraryIcon,
  ChartBarIcon,
  ClipboardDocumentCheckIcon,
  Cog6ToothIcon,
  CreditCardIcon,
  DocumentTextIcon,
  ExclamationTriangleIcon,
  IdentificationIcon,
  InformationCircleIcon,
  MapIcon,
  MinusCircleIcon,
  PencilSquareIcon,
  PhoneIcon,
  Squares2X2Icon,
  UserIcon,
} from "@heroicons/react/24/outline";

export const tabs = [
  { id: "personal", label: "Personal", icon: UserIcon },
  {
    id: "additional-info",
    label: "Additional Info",
    icon: InformationCircleIcon,
  },
  { id: "voyages", label: "Voyages", icon: BriefcaseIcon },
  {
    id: "experience-analysis",
    label: "Experience Analysis",
    icon: ChartBarIcon,
  },
  { id: "certificates", label: "Certificates", icon: IdentificationIcon },
  { id: "next-of-kin", label: "Next of Kin", icon: PhoneIcon },
  { id: "travel-info", label: "Travel Info", icon: MapIcon },
  { id: "appraisals", label: "Appraisals", icon: ClipboardDocumentCheckIcon },
  { id: "performance", label: "Performance", icon: ChartBarIcon },
  { id: "expenses", label: "Expenses", icon: BanknotesIcon },
  { id: "payroll", label: "Payroll", icon: CreditCardIcon },
  { id: "payroll-config", label: "Payroll Config", icon: Cog6ToothIcon },
  { id: "deductions", label: "Deductions", icon: MinusCircleIcon },
  { id: "allotments", label: "Allotments", icon: Squares2X2Icon },
  { id: "bank-details", label: "Bank Details", icon: BuildingLibraryIcon },
  { id: "remarks", label: "Remarks", icon: PencilSquareIcon },
  { id: "emergencies", label: "Emergencies", icon: ExclamationTriangleIcon },
  { id: "cv-applications", label: "CV & Applications", icon: DocumentTextIcon },
];
